pdfs:
  - newspaper: 'NY_NYT'
    crop: 
      left_edge: 0.02
      right_edge: 0.02
      top_edge: 0.022
      bottom_edge: 0.155
  - newspaper: 'WSJ'
    crop: 
      left_edge: 0.04
      right_edge: 0.04
      top_edge: 0.02
      bottom_edge: 0.025
  - newspaper: 'CA_SFC'
    crop: 
      left_edge: 0.04
      right_edge: 0.04
      top_edge: 0.015
      bottom_edge: 0.12

web:
  host: 0.0.0.0
  port: 5001

image:
  dpi: 300
  max_width: 1440
  max_height: 2560

refresh_scheduler:
  time: '06:00'
  timezone: 'America/Los_Angeles'
