pdfs:
  - newspaper: 'wsj'
    crop: 
      left_edge: 0.04
      right_edge: 0.04
      top_edge: 0.02
      bottom_edge: 0.025

web:
  host: 0.0.0.0
  port: 15001

image:
  dpi: 300
  max_width: 1440
  max_height: 2560

refresh_scheduler:
  time: '06:00'
  timezone: 'America/Los_Angeles'

source:
  base_url: 'https://d2dr22b2lm4tvw.cloudfront.net'
  pdf_slug: 'front-page.pdf'
  max_lookback_days: 5